### ISSUE TITLE
Performance for posting exceptions

### ISSUE THREAD

**Issue by Wulfheart** [LaraBug/larabug-app#87]
As an exception gets sent to the application the corresponding controller uses `dispatch_sync` which does not push a job to the queue. I think it should just be `dispatch`. 
If you agree I am going to open a PR for it.

https://github.com/LaraBug/larabug-app/blob/3da84141bbf3f99880e2a9c1af98de0ee12fc61d/app/Http/Controllers/Api/ApiController.php#L41

**Comment by Cannonb4ll** [comment]
We did have that in the past, but created a large number of processes in the background for Horizon and thus we disabled it temporarily. The Larabug server is just a 1GB 1Core server and not that powerful.

**Comment by Wulfheart** [comment]
Shouldn't it just spawn two or three processes? E.g. with ploi you can simply define how many queue workers you want to have,

**Comment by Cannonb4ll** [comment]
It does - but then there's a huge log. I don't think you understand how many requests we get in relation to the waiting list becomes in LaraBug when you use queued jobs (in this server setup). We've had this before, and disabled it because of performance issues.

It is not needed to dispatch them either - the way it is now is a perfect fit.

**Comment by Wulfheart** [comment]
Ah ok. Closing it then. Just found it odd.
